# Generated code do not commit.
file(TO_CMAKE_PATH "E:\\develop\\flutter" FLUTTER_ROOT)
file(TO_CMAKE_PATH "E:\\PMOB PRAK\\PBM\\tugas_pbm" PROJECT_DIR)

set(FLUTTER_VERSION "1.0.0+1" PARENT_SCOPE)
set(FLUTTER_VERSION_MAJOR 1 PARENT_SCOPE)
set(FLUTTER_VERSION_MINOR 0 PARENT_SCOPE)
set(FLUTTER_VERSION_PATCH 0 PARENT_SCOPE)
set(FLUTTER_VERSION_BUILD 1 PARENT_SCOPE)

# Environment variables to pass to tool_backend.sh
list(APPEND FLUTTER_TOOL_ENVIRONMENT
  "FLUTTER_ROOT=E:\\develop\\flutter"
  "PROJECT_DIR=E:\\PMOB PRAK\\PBM\\tugas_pbm"
  "FLUTTER_ROOT=E:\\develop\\flutter"
  "FLUTTER_EPHEMERAL_DIR=E:\\PMOB PRAK\\PBM\\tugas_pbm\\windows\\flutter\\ephemeral"
  "PROJECT_DIR=E:\\PMOB PRAK\\PBM\\tugas_pbm"
  "FLUTTER_TARGET=E:\\PMOB PRAK\\PBM\\tugas_pbm\\lib\\main.dart"
  "DART_DEFINES=RkxVVFRFUl9WRVJTSU9OPTMuMzguOA==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049YmQ3YTRhNmI1NQ==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049ZGIzNzNlYjg1YQ==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMC43"
  "DART_OBFUSCATION=false"
  "TRACK_WIDGET_CREATION=true"
  "TREE_SHAKE_ICONS=false"
  "PACKAGE_CONFIG=E:\\PMOB PRAK\\PBM\\tugas_pbm\\.dart_tool\\package_config.json"
)
